
columns_to_keep = [
   'Date Submitted',
   'Title',
   'Details',
   'Overall Rating',
   'Feedback: Food Rating',
   'Feedback: Drink Rating',
   'Feedback: Service Rating',
   'Feedback: Ambience Rating',
   'Feedback: Recommend to Friend',
   'Reservation: Date',
   'Reservation: Venue',
   'Reservation: Time',
   'Reservation: Overall Rating',
   'Reservation: Food Rating',
   'Reservation: Drinks Rating',
   'Reservation: Service Rating',
   'Reservation: Ambience Rating',
   'Reservation: Recommend to Friend',
   'Reservation: Feedback Notes',
   'Reservation: Updated Date',
   'Label: Dishoom',
   '👍',
   '👎',
   '💡',
   'Source',
   'Week',
   'Month',
   'Day_Name',
   'Day_Part',
   'Year',
   'Week_Year',
   'Month_Year',
   'date_for_filter',
   'Suggested to Friend',
   'New Overall Rating',
   'New Food Rating',
   'New Drink Rating',
   'New Service Rating',
   'New Ambience Rating'
   ]

options_for_classification = [
      'Welcome Not First Class',
      'Welcome Not Big Hearted',
      'Team Missed Special Occasions',
      'Team Missed Allergen / Dietary Requirement',
      'Team Service Not Big Hearted',
      'Team Service Not First Class',
      'Team Failed Service Recovery',
      'Bill Overcharged / Incorrect',
      'Overall End 2 End Poor Experience',
      'Overall Underwhelming / Average Experience',
      'Atmosphere',
      'Cleanliness / Safety Concerns',
      'Drink Delivery Slow',
      'Drinks Missing / Incorrect',
      'Drinks Average Feedback',
      'Drinks Poor Feedback',
      'Food Delivery Slow',
      'Food Missing / Incorrect',
      'Food Average Feedback',
      'Food Poor Feedback',
      'Dishoom General Offering',
      'Dishoom Design',
      'Dishoom Booking Policy / Queue',
      'Dishoom Price',
      'Dishoom Service Charge',
      'Too loud',
      'Other (No Clear Category)',
      '',
      'nan',]

# instead of using this We are going to read form the db
lookUpCafe = {
      'Dishoom Covent Garden': 'D1',
      'Dishoom Shoreditch': 'D2',
      'Dishoom Kings Cross': 'D3',
      'Dishoom Carnaby': 'D4',
      'Dishoom Edinburgh': 'D5',
      'Dishoom Kensington': 'D6',
      'Dishoom Manchester': 'D7',
      'Dishoom Birmingham': 'D8',
      'Dishoom Canary Wharf': 'D9'
   }
# need 20 emojis
list_of_emojis = [
   '🌏',
   '🌶️',
   '🍛',
   '🍚',
   '🍽️',
   '🥘',
   '🥗',
   '🍲',
   # add more
   '🍜',
   '🍝',
   '🍛',
]

service_keywords = [
      'service', 'waiter', 'waitress', 'waiters', 'waitresses', 'waitstaff',
      'host', 'hostess', 'hostesses', 'hosts', 'server', 'servers', 'staff',
      'price', 'bill', 'rush', 'rushing', 'rushes', 'rushed', 'rush','birthday',
      'pricing', 'priced', 'pricey', 'expensive', 'expensiveness', 'expensiveness',
   ]

key_words_related_to_ambience = ['atmosphere', 'ambience', 'chairs', 'tables', 'seating',
                                       'decor', 'interior', 'design', 'lighting', 'music', 'sound',
                                       'noise', 'noisy', 'quiet', 'loud', 'crowded', 'crowd', 'crowds',
                                       'crowding', 'clean', 'peaceful', 'toilets','parking','toilet',
                                       
]
   
food_keywords = [
      'cocktails', 'chilli', 'chutney', 'chutneys',
      'icecream', 'ice-cream', 'ice cream', 'icecreams', 'ice-creams', 'ice creams',
      'food', 'taste', 'tastes', 'flavor', 'flavors', 'dish', 'dishes', 'menu',
      'meal', 'meals', 'portions', 'portion', 'portioned', 'portioning', 'portioned',
      'quality', 'quantity', 'quantities', 'quantitied', 'quantitied', 'quantitied', 'Biryani']

keywords = service_keywords + key_words_related_to_ambience + food_keywords

menu_items_lookup = [
         'Akuri',
         'B & E Naan',
         'Bacon Naan',
         'Basmati Kheer',
         'Basmati Rice',
         'Bhel',
         'Big Bombay',
         'Black Daal',
         'Bowl of Greens',
         'BS Keema Pau',
         'BS Pau Bhaji',
         'Butter Corn OTC',
         'Butter Paanch',
         'Calamari',
         'Ch. Chawal (V)',
         'Ch. Puri(V)',
         'Chck Tikka Roll',
         'Cheese Naan',
         'Chicken Biryani',
         'Chicken Ruby',
         'Chicken Tikka',
         'Chilli Br Salad',
         'Chilli Chicken',
         'Choc Pud w/chil',
         'Choc Pud w/Cinn',
         'Chocolate Chai',
         'Chole Puri',
         'Dbl Bacon Naan',
         'Egg Naan',
         'Garlic Naan',
         'Gulab Jamun',
         'GunpowderPotato',
         'House Chaat',
         'Jackfruit Birya',
         'Kachumber',
         'Keema Per Eedu',
         'Kejriwal',
         'Khichia WChundo',
         'Kulfi Malai',
         'Kulfi Mango',
         'Kulfi Pistach.',
         'Lamb Chops',
         'Lamb Raan',
         'Lamb Raan Bun',
         'Lamb Samosas',
         'Mango& Fenn',
         'Masala Prawns',
         'Mattar Paneer',
         'Murgh Malai',
         'Mutton Chp Korm',
         'Mutton Pepper F',
         'Nihari',
         'Nihari Biryani',
         'Okra Fries',
         'Paneer Roll',
         'Paneer Tikka',
         'Parsi Omelette',
         'Pineapple Tikka',
         'Plain Naan',
         'Prawn Koliwada',
         'Raita',
         'Roomali Roti',
         'S & E Naan',
         'Saus Naan',
         'Sheekh Kabab',
         'Side Beans',
         'Tandoor  Roti',
         'Uttapam Stack',
         'Vada Pau',
         'Veg. Samosas',
         'Vegan Bombay',
         'Vegan Saus Naan',
         'Wrestler Naan',
         'Xmas Feast',
         'CCT',
      ]

drink_items_lookup = [
         'Beer',
         'Colaba Colada',
         'Mojito',
         'Mango Lassi',
         'Breakfast Lassi',
         'Coffee',
         'Americano',
         'Espresso',
         'Latte',
         '33cl Kingfisher',
         '65cl Kingfisher',
         'Aflatoon',
         'Amb. Viog Btl',
         'Bob Sauv Blanc',
         'Bolly Bellini',
         'Quinde Gls',
         'Quinde Malbec',
         'Sali Boti Full',
         'Sali Boti Half',
         'Sonia Negroni',
         'Sparkling Water',
         'Spumante Btl',
         'Spumante Gls',
         'Still Water',
         'Viceroy OF',
         'Watermelon Shbt',
         'Syrah Punctum',
         'Kohinoor Fizz',
         'Meenakshi Moj',
         'Nimbu Soda',
         'Oat Chai',
         'P. Grig Btl',
         'P. Grigio Gls',
         'Passionfr Shbt',
         'Peacock Cider',
         'Grenache Btl',
         'Grenache Gls',
         'Chai',
         'handra Bose',
         'Coloba Colada',
         'Cyrus Irani',
         'Dhoble',
         'Diet Coke 33cl',
         'Dish Esp Mtini',
         'Dishoom IPA',
         'East IndiaGim',
         'Folle Grillo Bt',
         'FolleGrillo Gls',
         'Fresh Orange J']
